package com.telegram.avtobot;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.view.*; import android.widget.*; import org.json.*; import java.util.*;

public class ScheduleActivity extends Activity {
 private static final String REPO="ajtnazarovasirin-wq/telegram-auto-bot-1"; private LinearLayout timesBox,daysBox; private TextView result; private android.content.SharedPreferences sp; private final String[] keys={"mon","tue","wed","thu","fri","sat","sun"}; private final String[] names={"Понедельник","Вторник","Среда","Четверг","Пятница","Суббота","Воскресенье"};
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.screen_section);sp=getSharedPreferences("settings",0);TextView title=findViewById(R.id.screenTitle),hint=findViewById(R.id.screenHint);title.setText("Расписание");hint.setText("Выбери дни и добавь одно или несколько времён отправки.");LinearLayout root=(LinearLayout)findViewById(R.id.content);daysBox=new LinearLayout(this);daysBox.setOrientation(LinearLayout.VERTICAL);root.addView(label("В какие дни отправлять"));for(int i=0;i<keys.length;i++){CheckBox c=new CheckBox(this);c.setText(names[i]);c.setTag(keys[i]);c.setChecked(sp.getBoolean("day_"+keys[i],true));daysBox.addView(c);}root.addView(daysBox);root.addView(label("Время отправки"));timesBox=new LinearLayout(this);timesBox.setOrientation(LinearLayout.VERTICAL);root.addView(timesBox);String saved=sp.getString("schedule_times","09:00");for(String t:saved.split(","))addTime(t.trim());Button add=new Button(this);add.setText("Добавить ещё время");add.setAllCaps(false);root.addView(add);add.setOnClickListener(v->addTime("12:00"));Switch enabled=new Switch(this);enabled.setText("Включить отправку по времени");enabled.setChecked(sp.getBoolean("enabled",false));root.addView(enabled);result=findViewById(R.id.result);Button action=findViewById(R.id.actionButton);action.setText("Сохранить расписание онлайн");action.setOnClickListener(v->{sp.edit().putBoolean("enabled",enabled.isChecked()).apply();publish();});findViewById(R.id.backButton).setOnClickListener(v->finish());}
 private TextView label(String s){TextView t=new TextView(this);t.setText(s);t.setTextSize(16);t.setTextColor(Color.rgb(71,84,103));t.setPadding(0,12,0,4);return t;}
 private void addTime(String value){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);EditText e=new EditText(this);e.setHint("ЧЧ:ММ");e.setText(value);e.setInputType(2);row.addView(e,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1));Button del=new Button(this);del.setText("Удалить");del.setAllCaps(false);row.addView(del);del.setOnClickListener(v->timesBox.removeView(row));timesBox.addView(row);}
 private void publish(){new Thread(()->{try{JSONArray days=new JSONArray();for(int i=0;i<daysBox.getChildCount();i++){View v=daysBox.getChildAt(i);if(v instanceof CheckBox&&((CheckBox)v).isChecked())days.put((String)v.getTag());}JSONArray schedules=new JSONArray();StringBuilder stored=new StringBuilder();for(int i=0;i<timesBox.getChildCount();i++){View v=timesBox.getChildAt(i);EditText e=(EditText)((ViewGroup)v).getChildAt(0);String time=e.getText().toString().trim();if(!time.matches("[0-9]{1,2}:[0-9]{2}"))continue;if(stored.length()>0)stored.append(", ");stored.append(time);schedules.put(new JSONObject().put("time",time).put("days",days));}sp.edit().putString("schedule_times",stored.toString()).apply();JSONObject cfg=new JSONObject().put("enabled",sp.getBoolean("enabled",false)).put("timezone",TimeZone.getDefault().getID()).put("schedules",schedules).put("chat_ids",new JSONArray().put(sp.getString("chat_target","@coding_222573g"))).put("topic",sp.getString("topic","Полезный совет по программированию")).put("instruction",sp.getString("instruction","Создай новый текст. Не повторяй предыдущие тексты.")).put("language","русский").put("provider","groq").put("model",sp.getString("model","openai/gpt-oss-120b")).put("history_limit",20);String token=sp.getString("github_token","");if(token.isEmpty()){runOnUiThread(()->result.setText("Сначала открой «Подключение GitHub» и введи token"));return;}GitHubClient.updateConfig(REPO,token,cfg.toString(2));runOnUiThread(()->result.setText("Расписание передано онлайн: "+stored));}catch(Exception e){runOnUiThread(()->result.setText("Ошибка: "+e.getMessage()));}}).start();}
}
