package com.telegram.avtobot;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.view.*; import android.widget.*; import java.util.*;

public class SectionActivity extends Activity {
 protected String section=""; private LinearLayout content; private TextView result; private android.content.SharedPreferences sp; private static final String REPO="ajtnazarovasirin-wq/telegram-auto-bot-1";
 protected EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setPadding(4,12,4,12);e.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){if(!section.equals("history"))save();}public void afterTextChanged(android.text.Editable e){}});return e;}
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.screen_section);sp=getSharedPreferences("settings",0);content=findViewById(R.id.content);result=findViewById(R.id.result);((Button)findViewById(R.id.backButton)).setOnClickListener(v->finish());build();}
 protected void build(){TextView title=findViewById(R.id.screenTitle),hint=findViewById(R.id.screenHint);Button action=findViewById(R.id.actionButton);if(section.equals("github")){title.setText("Подключение GitHub");hint.setText("Репозиторий уже подключён автоматически. Введи token один раз.");EditText t=input("GitHub token: Contents/Actions Read and write");t.setInputType(0x81);t.setText(sp.getString("github_token",""));content.addView(t);action.setText("Проверить и сохранить");action.setOnClickListener(v->{sp.edit().putString("github_token",t.getText().toString().trim()).apply();result.setText(t.getText().length()>0?"Подключение сохранено":"Введи token");});}
 else if(section.equals("telegram")){title.setText("Telegram-бот и чаты");hint.setText("Укажи токен бота и адрес канала или чата.");EditText t=input("Токен Telegram-бота");t.setInputType(0x81);t.setText(sp.getString("telegram_token",""));content.addView(t);EditText c=input("Канал или чат, например @coding_222573g");c.setText(sp.getString("chat_target","@coding_222573g"));content.addView(c);action.setText("Проверить Telegram");action.setOnClickListener(v->{sp.edit().putString("telegram_token",t.getText().toString().trim()).putString("chat_target",c.getText().toString().trim()).apply();result.setText("Данные Telegram сохранены. Бот должен быть администратором канала.");});}
 else if(section.equals("ai")){title.setText("AI-провайдер");hint.setText("Выбери один провайдер и введи его ключ и модель.");Spinner p=new Spinner(this);p.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Groq","Gemini","OpenAI / GPT"}));p.setSelection(sp.getString("provider","Groq").startsWith("Gem")?1:sp.getString("provider","Groq").startsWith("Open")?2:0);content.addView(p);EditText k=input("API-ключ выбранного провайдера");k.setInputType(0x81);content.addView(k);EditText m=input("Название модели");m.setText(sp.getString("model","openai/gpt-oss-120b"));content.addView(m);EditText topic=input("Тема текста");topic.setText(sp.getString("topic","Полезный совет по программированию"));content.addView(topic);EditText instruction=input("Промпт и правила повторов");instruction.setMinLines(3);instruction.setText(sp.getString("instruction","Создай новый текст. Не повторяй предыдущие тексты, если я явно не разрешил повторы."));content.addView(instruction);action.setText("Сохранить AI-настройки");action.setOnClickListener(v->{String pv=p.getSelectedItem().toString();sp.edit().putString("provider",pv).putString("model",m.getText().toString().trim()).putString("topic",topic.getText().toString().trim()).putString("instruction",instruction.getText().toString().trim()).apply();if(pv.startsWith("Groq"))sp.edit().putString("groq_key",k.getText().toString().trim()).apply();else if(pv.startsWith("Gem"))sp.edit().putString("gemini_key",k.getText().toString().trim()).apply();else sp.edit().putString("openai_key",k.getText().toString().trim()).apply();result.setText("AI-настройки сохранены");});}
 else if(section.equals("schedule")){title.setText("Расписание");hint.setText("Укажи одно или несколько времён через запятую.");EditText times=input("Например: 09:00, 14:30, 20:00");times.setText(sp.getString("schedule_times","09:00"));content.addView(times);Switch en=new Switch(this);en.setText("Включить отправку по времени");en.setChecked(sp.getBoolean("enabled",false));content.addView(en);action.setText("Сохранить расписание онлайн");action.setOnClickListener(v->{sp.edit().putString("schedule_times",times.getText().toString().trim()).putBoolean("enabled",en.isChecked()).apply();publish(result);});}
 else if(section.equals("history")){title.setText("История и отчёт");hint.setText("Последние результаты работы онлайн-бота.");TextView h=new TextView(this);h.setText(sp.getString("last_report","История появится после первого запуска."));h.setTextSize(16);content.addView(h);action.setText("Обновить");action.setOnClickListener(v->h.setText(sp.getString("last_report","История пока пуста.")));}}
 private void save(){}
 private void publish(TextView out){String t=sp.getString("github_token","");if(t.isEmpty()){out.setText("Сначала подключи GitHub");return;}new Thread(()->{try{String cfg="{\"enabled\":"+sp.getBoolean("enabled",false)+",\"timezone\":\""+TimeZone.getDefault().getID()+"\",\"schedules\":[{\"time\":\""+sp.getString("schedule_times","09:00").split(",")[0].trim()+"\",\"days\":[\"mon\",\"tue\",\"wed\",\"thu\",\"fri\",\"sat\",\"sun\"]}],\"chat_ids\":[\""+sp.getString("chat_target","@coding_222573g")+"\"],\"topic\":\""+sp.getString("topic","")+"\",\"instruction\":\""+sp.getString("instruction","")+"\",\"provider\":\"groq\",\"model\":\""+sp.getString("model","openai/gpt-oss-120b")+"\"}";GitHubClient.updateConfig(REPO,t,cfg);runOnUiThread(()->out.setText("Расписание передано онлайн"));}catch(Exception e){runOnUiThread(()->out.setText("Ошибка: "+e.getMessage()));}}).start();}
}
