package com.telegram.avtobot;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.text.InputType; import android.text.method.PasswordTransformationMethod; import android.text.method.HideReturnsTransformationMethod; import android.view.*; import android.widget.*; import org.json.*; import java.util.*;

public class SectionActivity extends Activity {
 protected String section=""; private LinearLayout content; private TextView result; protected android.content.SharedPreferences sp; private static final String REPO="ajtnazarovasirin-wq/telegram-auto-bot-1";
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.screen_section);sp=getSharedPreferences("settings",0);content=findViewById(R.id.content);result=findViewById(R.id.result);((Button)findViewById(R.id.backButton)).setOnClickListener(v->finish());build();}
 private TextView label(String s){TextView t=new TextView(this);t.setText(s);t.setTextSize(15);t.setTextColor(Color.rgb(71,84,103));t.setPadding(0,14,0,3);return t;}
 private EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(16);e.setPadding(4,10,4,10);return e;}
 private EditText secret(String hint,String value){EditText e=field(hint,value);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);e.setTransformationMethod(PasswordTransformationMethod.getInstance());Button eye=new Button(this);eye.setText("Показать");eye.setAllCaps(false);eye.setOnClickListener(v->{boolean hidden=e.getTransformationMethod()!=null; e.setTransformationMethod(hidden?HideReturnsTransformationMethod.getInstance():PasswordTransformationMethod.getInstance());eye.setText(hidden?"Скрыть":"Показать");});LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(e,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1));row.addView(eye,new LinearLayout.LayoutParams(110,LinearLayout.LayoutParams.WRAP_CONTENT));content.addView(row);return e;}
 private void add(View e){content.addView(e);}
 private void build(){TextView title=findViewById(R.id.screenTitle),hint=findViewById(R.id.screenHint);Button action=findViewById(R.id.actionButton);
  if(section.equals("github")){title.setText("Подключение GitHub");hint.setText("Репозиторий уже заполнен автоматически. Нужен только token с правами Contents и Actions: Read and write.");EditText t=secret("GitHub token",sp.getString("github_token",""));action.setText("Проверить и сохранить token");action.setOnClickListener(v->{sp.edit().putString("github_token",t.getText().toString().trim()).apply();result.setText(t.getText().length()>0?"Token сохранён. Репозиторий подключён автоматически.":"Вставь GitHub token.");});}
  else if(section.equals("telegram")){title.setText("Telegram и чаты");hint.setText("Введи токен бота и канал. Для канала можно указать @username.");EditText t=secret("Токен Telegram-бота",sp.getString("telegram_token",""));EditText c=field("Канал или чат, например @coding_222573g",sp.getString("chat_target","@coding_222573g"));add(c);Button sync=new Button(this);sync.setText("Загрузить и выбрать чаты");sync.setAllCaps(false);content.addView(sync);sync.setOnClickListener(v->{sp.edit().putString("telegram_token",t.getText().toString().trim()).putString("chat_target",c.getText().toString().trim()).apply();result.setText("Сначала добавь бота в нужные группы/каналы, затем повтори загрузку.");});action.setText("Сохранить Telegram");action.setOnClickListener(v->{sp.edit().putString("telegram_token",t.getText().toString().trim()).putString("chat_target",c.getText().toString().trim()).apply();result.setText("Telegram сохранён. Для канала бот должен быть администратором.");});}
  else if(section.equals("ai")){title.setText("AI-провайдер и модель");hint.setText("Выбери провайдера, введи его ключ, затем загрузи реальные модели.");Spinner p=new Spinner(this);String[] ps={"Groq","Gemini","OpenAI / GPT"};p.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ps));String old=sp.getString("provider","Groq");p.setSelection(old.startsWith("Gem")?1:old.startsWith("Open")?2:0);content.addView(p);EditText k=secret("API-ключ выбранного провайдера",keyFor(old));EditText m=field("Выбранная модель",modelFor(old));add(m);Button load=new Button(this);load.setText("Загрузить реальные модели");load.setAllCaps(false);content.addView(load);EditText topic=field("Тема текста",sp.getString("topic","Полезный совет по программированию"));add(topic);EditText ins=field("Промпт и правила повторов",sp.getString("instruction","Создай новый текст. Не повторяй предыдущие тексты, если я явно не разрешил повторы."));ins.setMinLines(4);add(ins);p.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> x){}public void onItemSelected(AdapterView<?> x,View v,int pos,long id){if(pos==1){k.setText(sp.getString("gemini_key",""));m.setText(sp.getString("gemini_model","gemini-3.6-flash"));}else if(pos==2){k.setText(sp.getString("openai_key",""));m.setText(sp.getString("openai_model","gpt-5-mini"));}else{k.setText(sp.getString("groq_key",""));m.setText(sp.getString("groq_model","openai/gpt-oss-120b"));}}});load.setOnClickListener(v->{String pv=p.getSelectedItem().toString();String key=k.getText().toString().trim();if(key.isEmpty()){result.setText("Сначала введи API-ключ выбранного провайдера.");return;}new Thread(()->{try{JSONArray a=ApiClient.listModels(pv,key);String[] ids=new String[a.length()];for(int i=0;i<a.length();i++)ids[i]=a.getString(i);runOnUiThread(()->{if(ids.length==0){result.setText("Провайдер не вернул модели для этого ключа.");return;}new AlertDialog.Builder(this).setTitle("Выбери модель").setItems(ids,(d,w)->{m.setText(ids[w]);result.setText("Выбрана модель: "+ids[w]);}).show();});}catch(Exception e){runOnUiThread(()->result.setText("Ошибка загрузки моделей: "+e.getMessage()));}}).start();});action.setText("Сохранить AI-настройки");action.setOnClickListener(v->{String pv=p.getSelectedItem().toString();android.content.SharedPreferences.Editor e=sp.edit().putString("provider",pv).putString("topic",topic.getText().toString().trim()).putString("instruction",ins.getText().toString().trim());if(pv.startsWith("Groq"))e.putString("groq_key",k.getText().toString().trim()).putString("groq_model",m.getText().toString().trim());else if(pv.startsWith("Gem"))e.putString("gemini_key",k.getText().toString().trim()).putString("gemini_model",m.getText().toString().trim());else e.putString("openai_key",k.getText().toString().trim()).putString("openai_model",m.getText().toString().trim());e.apply();result.setText("AI-провайдер и модель сохранены: "+m.getText());});}
  else if(section.equals("schedule")){title.setText("Расписание");hint.setText("Настрой дни недели и любое количество времён отправки.");TextView note=label("Конструктор расписания находится на отдельном экране.");add(note);action.setText("Открыть расписание");action.setOnClickListener(v->{startActivity(new Intent(this,ScheduleActivity.class));});}
  else if(section.equals("history")){title.setText("История и отчёт");hint.setText("Последние результаты работы онлайн-бота.");TextView h=new TextView(this);h.setText(sp.getString("last_report","История появится после первого запуска."));h.setTextSize(16);content.addView(h);action.setText("Обновить историю");action.setOnClickListener(v->h.setText(sp.getString("last_report","История пока пуста.")));}
 }
 private String keyFor(String p){return p.startsWith("Gem")?sp.getString("gemini_key",""):p.startsWith("Open")?sp.getString("openai_key",""):sp.getString("groq_key","");}
 private String modelFor(String p){return p.startsWith("Gem")?sp.getString("gemini_model","gemini-3.6-flash"):p.startsWith("Open")?sp.getString("openai_model","gpt-5-mini"):sp.getString("groq_model","openai/gpt-oss-120b");}
}
