package com.telegram.avtobot;

import android.app.*; import android.content.*; import java.util.*;

public final class Sender {
 private Sender(){}
 public static void run(Context c){AppPrefs p=new AppPrefs(c);android.content.SharedPreferences h=c.getSharedPreferences("history",0);android.content.SharedPreferences chats=c.getSharedPreferences("chats",0);if(p.token().isEmpty()||p.key().isEmpty()){h.edit().putString("status","Ошибка: не заполнен Telegram или AI-ключ").apply();return;}try{
  Set<String> old=new HashSet<>(h.getStringSet("texts",new HashSet<>()));String ins=p.instruction();String low=ins.toLowerCase();boolean repeat=low.contains("повтор")||low.contains("repeat")||low.contains("одинаков");String prompt="Тема: "+p.topic()+"\nИнструкция: "+ins+"\nЯзык: "+p.language()+"\n"+(repeat?"Повторы разрешены по инструкции пользователя.":"Создай новый текст и не повторяй эти тексты: "+old)+"\nМаксимум "+p.maxLength()+" символов.";h.edit().putString("status","Запрос отправлен в "+p.provider()).apply();String text=ApiClient.generate(p.provider(),p.key(),p.model(),prompt,p.maxLength());if(!repeat&&old.contains(text))text=ApiClient.generate(p.provider(),p.key(),p.model(),prompt+"\nСделай формулировку другой.",p.maxLength());h.edit().putString("status","Ответ ИИ получен").apply();
  String setName=p.allChats()?"all_ids":"ids";Set<String> set=chats.getStringSet(setName,new HashSet<>());String direct=c.getSharedPreferences("settings",0).getString("chat_target","");List<String> targets=new ArrayList<>(set);if(targets.isEmpty()&&!direct.isEmpty())targets.add(direct);if(targets.isEmpty()){h.edit().putString("status","Ошибка: не выбран чат или канал").apply();return;}int ok=0;StringBuilder report=new StringBuilder();for(String target:targets)try{String r=ApiClient.telegramSend(p.token(),target,text);if(new org.json.JSONObject(r).optBoolean("ok",false))ok++;chats.edit().putString("last_"+target,r).apply();report.append("\n✓ ").append(target);}catch(Exception e){chats.edit().putString("last_"+target,"ERROR: "+e.getMessage()).apply();report.append("\n✗ ").append(target).append(": ").append(e.getMessage());}Set<String> updated=new HashSet<>(old);updated.add(text);while(updated.size()>10)updated.remove(updated.iterator().next());h.edit().putStringSet("texts",updated).putString("last_text",text).putString("status","Успешно отправлено: "+ok+" из "+targets.size()+report).putLong("last_sent",System.currentTimeMillis()).apply();scheduleCheck(c,p.checkDelay());
 }catch(Exception e){h.edit().putString("status","Ошибка: "+e.getMessage()).putString("last_error",e.getMessage()).apply();}}
 private static void scheduleCheck(Context c,int minutes){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);Intent i=new Intent(c,CheckReceiver.class);PendingIntent pi=PendingIntent.getBroadcast(c,91,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);long at=System.currentTimeMillis()+Math.max(1,minutes)*60000L;if(android.os.Build.VERSION.SDK_INT>=23)am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);else am.set(AlarmManager.RTC_WAKEUP,at,pi);}
}
