#CodeAssist project settings
#Mon Aug 24 00:21:20 GMT+06:00 2026
tree.expanded.Project=root\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/project/app/src/main/res\nmodule\:app\nroot\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/project/app/src/main/java\nworkspace
